version: '3.4'
services:
  postgres:
   image: postgres
   ports:
    - "5432:5432"
   volumes:
    - postgres-volume:/var/lib/postgresql/data
   environment:
    - POSTGRES_USER=ifeds
    - POSTGRES_PASSWORD
    - POSTGRES_DB=ifeds
networks:
  default:
   external:
     name: ${IFEDS_NETWORK:-ifeds-network}
volumes:
   postgres-volume:
     external: true

